name: SportsDay
version: '${version}'
main: org.macausmp.sportsday.SportsDay
api-version: '1.21'
authors: [ JJGP ]
description: "The MacauSMP SportsDay plugin"
commands:
  event:
    usage: "/event (start|load|save|pause|unpause|terminate|join|leave|score|info) <argument>"
    description: "Event management command"
    permission: op
  sgb:
    usage: "/sgb"
    description: "Open Sports Governing Body gui"
    aliases: ["sports-governing-body"]
    permission: op
  contestant:
    usage: "/contestant (join|leave|score|list) <argument>"
    description: "Contestant management command"
    permission: op
  register:
    usage: "/register <number>"
    description: "Register as a contestant"
  unregister:
    usage: "/register"
    description: "Unregister as a contestant"
  menu:
    usage: "/menu"
    description: "Open menu gui"
  customize:
    usage: "/customize"
    description: "Open customize gui"
  ping:
    usage: "/ping <player>"
    description: "Query player's ping"