name: SportsDay
version: '${version}'
main: org.macausmp.sportsday.SportsDay
api-version: '1.20'
authors: [ JJGP ]
description: "The MacauSMP SportsDay plugin"
commands:
  competition:
    usage: "/competition (start|end|join|leave|score|info) <argument>"
    description: "Competition hosting command"
    permission: op
  competitiongui:
    usage: "/competitiongui"
    description: "Open competition gui"
    permission: op
