name: SportsDay
version: '${version}'
main: org.macausmp.sportsday.SportsDay
api-version: '1.21'
authors: [ JJGP ]
description: "The MacauSMP SportsDay plugin"
commands:
  competition:
    usage: "/competition (start|load|save|pause|unpause|terminate|join|leave|score|info) <argument>"
    description: "Competition hosting command"
    permission: op
  competitiongui:
    usage: "/competitiongui"
    description: "Open competition gui"
    permission: op
  register:
    usage: "/register <number>"
    description: "Register as a contestant"
  unregister:
    usage: "/register"
    description: "Unregister as a contestant"
  menu:
    usage: "/menu"
    description: "Open menu gui"
  customize:
    usage: "/customize"
    description: "Open customize gui"
  ping:
    usage: "/ping <player>"
    description: "Query player's ping"